### ISSUE TITLE
Where's "close right tabs" and "close left tabs"?

### ISSUE THREAD

**Issue by jbclem** [piroor/multipletab#112]
Using Firefox 25.0.1.  Just installed multipletabhandler...I see "close all tabs" but not the ones I needed most: "close right tabs" and "close left tabs".  Is it compatible with this version of Firefox?

I also see "close similar tabs", "close tabs to the top", "close other similar tabs", "reload left tabs", "reload right tabs", "reload all tabs", etc...  Just missing the ones I wanted.

John

**Comment by jbclem** [comment]
I'm noticing that "close tabs to left" has now appeared, but still no "close tabs to right" no matter which tab I choose.

**Comment by piroor** [comment]
Firefox 25 is already out of date and Multiple Tab Handler doesn't support it anymore...

**Comment by jbclem** [comment]
Do you have an archived older version of Multiple Tab Handler that would work for me.  Firefox 25 isn't out of date to me, and there's isn't much that would entice me into a newer version.

**Comment by piroor** [comment]
Old versions are available at https://addons.mozilla.org/firefox/addon/multiple-tab-handler/versions/

I mean that Firefox 25 is officially out of date. My addon sometimes work on very old versions of Firefox, but basically I believe that officially-supported versions (currently, it is Firefox 38 and Firefox 43) are versions that my addons must support to.

**Comment by jbclem** [comment]
Thanks, the older versions will be very useful.  In the meantime I did install the current version in Palemoon 25.5.0.1 and it seems to be working.  I wonder if you've considered adding a "stop all tabs" series, or "stop all tabs to the right".  That's something I need all the time since I open up windows with 27 tabs and there are always some that keep updating themselves ad nauseum.

**Comment by chronometric** [comment]
@jbclem: you might want to add a different feature request as its own new issue, to keep his book keeping tidy and get attention. Stopping multiple tabs might be within a similar scope to the close/reload/etc logistical functions, but I doubt it would be that useful. If you mean pages keep refreshing or loading new content, simply hitting stop will probably only stop it until the next cycle. Running the **NoScript **security addon in a more recent Firefox version will mean that pages can't use active content without your permissions, and this will literally never happen again. 

A good reason to update browsers is that a lot of things go on under the hood, and who knows how many potential security problems have been addressed in 2.5 years. Also, unless you keep your old addons that were supported by that particular version of code, each new update will increase the chances that the new code will no longer interface properly, and break, like happened to this feature. Something to think about ^^

Since this is working in current browsers (just checked too), you could hit the Close Issue button if you're satisfied about that feature. ^^

**Comment by piroor** [comment]
Outdated.
