### ISSUE TITLE
[Tab Groups v2 Conflict] move to group broken 

### ISSUE THREAD

**Issue by jmain33** [piroor/multipletab#118]
Incompatible with the recently updated [Tab Groups] (https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/) extension:

Selecting multiple tabs, then right-clicking and choosing move to group in the context menu followed by one of the subgroups -> only the tab that was right-clicked upon is moved (without the others) and **it is not moved to the chosen group**; it is, instead, moved to a non-existent/invisible new group. Each tab that this is done for is moved to a separate new group. The tabs, at first, appear to be lost, because **the newly created groups are invisible**.

After restarting Firefox each erroneously created new group can be seen, containing the singular tab that was moved. Also, after restart, the _move to group_ sub-menu no longer shows the list of current groups; only a single entry, _**New Group**_, is available.

It looks like you need to change MTH to correctly align with tab groups created by Tab Groups v2.

* Using 'move to group' when not selecting multiple tabs still works fine, it is only when one tries to move several tabs at once that the bug surfaces

**Comment by piroor** [comment]
Because now Tab Groups is an external project (not a built-in feature of Firefox), I have less motivation to maintain MTH for it - I'm already full by other problems appearing without extra addons. This I need pull requests from users who ordinary use MTH with Tab Groups.

**Comment by dequis** [comment]
Are there relevant fixes in the recent git revisions? I installed the unsigned xpi from http://piro.sakura.ne.jp/xul/_multipletab.html.en and it seems to have fixed the issue of moving only the first tab to invisible groups. But maybe it's something that doesn't happen every time?

(Just upgraded to the aurora channel, ff 49.0a2, and grabbed the latest build because I thought the issues were e10s related, but it matches this description perfectly)

**Comment by Quicksaver** [comment]
Fixed by https://github.com/Quicksaver/Tab-Groups/commit/4e85cf4c8f3d24b6f75bd6e9056e637ac30152ba
