### ISSUE TITLE
Open tab (or selected tabs) in ...

### ISSUE THREAD

**Issue by fake150816** [piroor/multipletab#128]
There is an [addon](https://addons.mozilla.org/ru/firefox/addon/open-with/) that creates buttons to open current tab in some other program (browser, etc). But it spies for user activity and can't work with multiple tabs. Maybe, you will add an option to the context menu or tab and multiple selected tabs for open them in some other software, specified in MTH settings?

**Comment by piroor** [comment]
I have no plan to add any extra feature like the addon to MTH, instead I believe that I should add just a menu item for the addon. But currently I have less time to maintain my addons, so I need contributions from people, especially compatibility problems with other addons which are not used by me...

By the way, I've read the source code of the addon https://github.com/darktrojan/openwith/blob/VERSION_6.7.2/modules/dataCollection.jsm and I think that it seems enough safe, because it collects only the addon's preferences and platform type/versions.

**Comment by VideoPod** [comment]
My primary concern is with security. I don't understand why I have to add Open With to have Mozilla Thunderbird open links using Chrome instead of the Windows 10 Bing Thing... Why is that not included as an option in the core code of Thunderbird and who do I talk to about this?

**Comment by piroor** [comment]
Now MTH just provides a feature to select tabs dragging, and extra features for selected tabs are provided by other addons.
