### ISSUE TITLE
When both Multiple Tab Handler and Tab Mix Plus are enabled, tabs can no longer be moved/re-ordered via drag and drop

### ISSUE THREAD

**Issue by majdnem** [piroor/multipletab#139]
When both Multiple Tab Handler and Tab Mix Plus are enabled, tabs can no longer be moved/re-ordered via drag and drop. Have updated firefox and extensions. Problem started today, 28th Oct 2016. Poassibly unrelated, but this coincided with Windows 10 wanting a restart to install updates. Have tried multiple combinations of options within both Multiple Tab Handler and Tab Mix Plus, but the problem recurs. Best workaround I have found to retain maximum functionality is to disable MTH, which i would prefer to avoid...

**Comment by paulescobar** [comment]
I have this exact same problem. 
It is impossible to move tabs if both Tab Mix Plus & Multiple Tab Handler are installed.

It has nothing to do with operating system. 
OP is on Win10. 
I am on Win8.1

I tested various settings & scenarios. 
Nothing I tried could solve the problem.

**Comment by LL25255252** [comment]
Same problem with :
Cyberfox 49.0.1
Tab Mix Plus 0.5.0.1
MTH 0.8.2016090602
Win 7 x64

**Comment by troubleshooter75** [comment]
I have the same problem, and same results.
Occurs on both my computers (32 bit):
Vista
Windows 7
latest versions Firefox and said extensions.

I associated it with the update to Firefox to 49
Both 49.0.1 and continued when 49.0.2 updated.
(my Vista refuses to update windows [subject for another place and time; eh], so no windows updates have occurred on the Vista machine since they worked together correctly).

Tab will drag with mouse, but remaining tabs will not 'shuffle', and it leaves a blank tab spot behind; and when the dragged tab is released, it pops back to the original position - it will not 'place' anywhere else.
**Also, the 'placement arrow' does not appear and follow the mouse's positioning.**
Oh, the placement is arrow working otherwise - it shows normally when dragging a link to a position and placing a tab; so it is not that.

The mouse drag function is just not invoking the placement function correctly.
I did not try to drag to a new window...

Mr KL

**Comment by troubleshooter75** [comment]
I found a solution possibly.

I removed, then re-installed MTH.
It has worked since then.

I have not restored my preferences to previous settings yet, so I don't know if this is the answer.

I tried several combinations of TMP reset to defaults, safe mode, and a fresh FF profile; progressively changing things. (the fresh profile worked, my existing FF profile still did not)
I tried setting TMP settings to default, no change; and back, no change.
Nothing fixed it until I removed and reinstalled MTH.

It seems to me the last update (on top of an existing install) may have broke it.
I won't know for sure until I compare restoring my original settings, and see if it breaks it, or it continues to work after I have everything matching the original configurations.
(It is so time consuming to do all this, trying all the combinations!)

There is a thread on TMP here:
[http://tabmixplus.org/forum/viewtopic.php?f=3&t=19581&p=71225#p71225](url)

Hope this helps.
Mr KL

**Comment by LL25255252** [comment]
@troubleshooter75 kudos to you for taking the time to investigate this conflict.
The 2 URLs at the end of your post are correct but they point to a 404.

**Comment by troubleshooter75** [comment]
Thank you LL25255252.
(what does LL25255252 mean? haha)

Strange; when I mouse over the links I posted, they don't show the URLs showing!
They show some Github URL!
I used the URL tool, and entered only the paste from my pages (which obviously went in because it shows the URL), BUT, the name ONLY is right, the underlying URL is a Github 404 URL!
Apparently the URL tool here is broken!

If you paste the URLs shown, they should work (mouse-over shows wrong here too).
If they still don't work, it is probably because I am logged in, and I will link URLs in logged out format.
Let me know...
I used the URL tool in the post message form, and I only pasted the  from the page, I added no additional name or other. (and it shows the URL I pasted, just has an underlying URL that I didn't add).
[baffled]

Mr KL

**Comment by LL25255252** [comment]
@troubleshooter75's post on TMP forum :
http://tabmixplus.org/forum/viewtopic.php?f=3&t=19581&p=71225#p71225
and also here here:
http://tabmixplus.org/forum/viewtopic.php?f=2&t=19705&p=71201#p71201

**Comment by LL25255252** [comment]
I posted STR (steps to reproduce) at the TMP forum. 
Here - http://tabmixplus.org/forum/viewtopic.php?p=71240#p71240

**Comment by piroor** [comment]
Outdated.
