### ISSUE TITLE
Web extension

### ISSUE THREAD

**Issue by rayman89** [piroor/multipletab#154]
Will it be possible to make this addon a web extension?/ Will you update it for firefox 57+?

**Comment by AzureRaptor** [comment]
I sincerely hope this will happen.  I can't find any other addon that really does all the things this one does!

**Comment by grahamperrin** [comment]
https://github.com/piroor/multipletab/issues/148#issuecomment-299809744: 

> … Multiple Tab Handler… must be reconstructured as pure WebExtensions addons. I hope to spend more time to fix other resolvable bugs, with my very few free time.

**Comment by rayman89** [comment]
The point of fixing other resolvable bugs will be ending soon unless he plans to keep it alive for the ESR and palemoon version so I think it's still a valid question at this point.

**Comment by boldcompany** [comment]
It would be wonderful if this plugin continues as a web extension into FF57+!

**Comment by davestechshop** [comment]
I love this add-on. Security forces me to upgrade to FF 57. But I cannot imagine FF without this add-on. Please make it a pure WebExtension. I'm willing to donate to support the work.

**Comment by grahamperrin** [comment]
> … willing to donate … 

@piroor FYI https://discourse.mozilla.org/t/-/17734/41?u=grahamperrin

**Comment by piroor** [comment]
Now WebExtensions-based version is available. Due to limitations of WebExtensions, you cannot operate Firefox's native tabs - instead you need to use MTH's toolbar panel. (Or, if you install Tree Style Tab, selection behavior is available on TST's sidebar tabs.)
https://addons.mozilla.org/firefox/addon/multiple-tab-handler/

Thanks to your will for donation, but I have no plan to get it for now...

**Comment by pmorch** [comment]
I believe this issue can be closed, as it currently is a Web Extension
