### ISSUE TITLE
Error while selecting tabs in quick succession with control

### ISSUE THREAD

**Issue by rayman89** [piroor/multipletab#174]
When selecting tabs in quick succession with control the addon sometimes would select an other random tab or clear the selection.

**Comment by piroor** [comment]
It is an intentional behavior. If you click non-active tab item, the active tab or last clicked tab is also automatically selected. This is similar to Windows Explorer's file selection behavior.

However I agree that it is confusable on the panel. On Tree Style Tab's sidebar, there is visually active tab and the behavior above is natural. On the other hand, MTH's panel has no visual feedback for active or last clicked item, so there is no hint to know the behavior.

**Comment by piroor** [comment]
By recent commits, now the last clicked tab has a visual feedback. Moreover, initially the current tab is treated as the last clicked tab by default. If you see any odd selection for not a last clicked tab, please add a comment with detailed steps to reproduce.

**Comment by rayman89** [comment]
I tested a bit more and noticed what the "issue" is. When someone clicks and moves the mouse too quickly sometimes what ends up doing is dragging the mouse while holding down the click and the dragging while holding control on your addon has an other functionality. So for example if I have 5 tabs and selected 1 2 and 3 and then went to select 4 but actually instead of control click did drag the mouse while holding control and click the addon restarts the selection and selects only tab 4. So there is no real issue people would just need to either do it slower or use the drag selection from the start. 

You can close this if you want or even better add a 200 ~ 300ms delay for the drag selection to prevent the 2 kinds of selection from conflicting with each other.

**Comment by piroor** [comment]
Ctrl-drag to modify selection is not implemented yet, sorry.

**Comment by piroor** [comment]
I didn't implemented those actions because basically MTH was designed to work on actual tabs and ctrl/shift-drag on tabs can be used to other actions. So only long-press to start selection by dragging was available. Now you'll see the behavior when you use MTH with Tree Style Tab.

To be honest, current WebExtensions-based MTH was originally made just for Tree Style Tab, aimed to reintroduce behaviors of the combination of legacy TST + MTH. Other usecase including the toolbar button popup are just optional features. I added those features with minimum effort, just to release WE-MTH as a standalone addon. Thus the panel is actually not enough useful.

Due to such a background, I have very few motivation to improve the panel itself. Instead I hope to spend more time to improve UX around the combination of MTH + TST, and I won't improve the panel aggressively. If you really want to use the panel as the primary UI, contribution from people who actually need that is really needed.

Current popup panel is based on a common codes shared to the behavior above

**Comment by rayman89** [comment]
Seems to be a misunderstanding in our communication. I'm not requesting being able to control-drag. Selection is ok the way it's now what I asked was a really unimportant change so don't worry you can close this.

BTW I would love to contribute to the code so the changes I suggested could be implemented but my knowledge of programing is almost 0.
