### ISSUE TITLE
Can I disable long press effect?

### ISSUE THREAD

**Issue by toruyamaguchi** [piroor/multipletab#205]
## Short description
**Englishe**
I use TST and MTH.
I want to "selecting" tabs (this "selecting" means that the tabs' has Multiple Tab Handler's context menu) when I use only `Shift`-key or `Ctrl`-key.
Can I make the setting that the state "selecting" tabs does not occur when I hold down tabs?
Also, is it possible to set the length of time it takes to change to "selecting" state?

**Japanese**
ツリー型タブとマルチプルタブハンドラを使っています。
`Shift`キーか`Ctrl`キーだけを押したときだけタブの「選択」（ここでいう「選択」とはコンテキストメニューにマルチプルタブハンドラのものが表示される状態）をしたいです。
長押しをした時にタブを「選択」した状態にならないような設定は可能ですか？
また、「選択」状態にするまでの時間を任意に設定することは可能ですか？

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install MTH.
 3. Install TST.
 4. Long press on tabs in TST side-bar.

## Expected result

**English**
Nothing happens when I hold down tab or tabs.

**Japanese**
タブを長押しをしたときに何も起こらない。

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 61
 * Version (or revision) of Multiple Tab Handler: 2.0.13
 * Version of Tree Style Tab: 2.4.24

**Comment by toruyamaguchi** [comment]
I am able to realize my hope by setting "startDragTimeout".
For example, the value is set to 5000.

Thank you so much!

**Comment by joshgold22** [comment]
I'd still like to see this as a simple checkbox in the MTH preferences:   E.g.., "Drag after long press to select multiple tabs."

Most important reason: I think this would make it more discoverable that MTH *has* two behaviors, depending how long you press.  It took me a long, confusing time to figure that out.  Before (and even today if I don't think about it) I would often spend a lot of time selecting a number of tabs, meaning to drag to a new window.  If I dragged a little too slow, it would go into selection mode instead of dragging - I would lose all my work and not know why!)

Of course, you could also include the delay if you add the preference.  Perhaps that's optional/advanced, I could go either way..

(Honestly, if it were me I would default to *not* having drag to select after a delay, because I think the behavior is fussy to use and easy to get an unexpected, even if it's handy if you know it.)

**Comment by piroor** [comment]
@joshgold22 Please note that there are multiple problems.

 * Starting of new multiselection by long press on already multiselected active tab is not an intentional behavior. The active tab and other multiselected tabs should be dragged when you start dragging on the active tab, even if you press the mouse button too long.
 * "How long press" config is now under control of TST, but I agree that it should be controlled by MTH itself.
 * "Start dragging by long press" option of MTH is actually affect to both selection popup (MTH's UI) and TST's sidebar. There should be two separate options for MTH's popup and TST's sidebar.

By recent commits on TST and MTH, now these problems are fixed for me. On the combination of the next releases of TST and MTH, you'll see more-easily-draggable multiselected tabs.

**Comment by joshgold22** [comment]
That sounds good - but could you clarify, what is the intended behavior for a long versus short click?  (And are you saying the answer is different for TST and MTH?)  What *should* happen if I long-click?
