### ISSUE TITLE
Tab context menu and multiselect tabs on firefox 62+

### ISSUE THREAD

**Issue by rayman89** [piroor/multipletab#208]
Can you make the addon show it's tab context menu when multiple tabs are selected using firefox's "browser.tabs.multiselect" available on firefox 62+?

**Comment by piroor** [comment]
Of course it is planned, but still there are some missing feature, for example [ability to set "multiselected" status to tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1479129 "1479129 - Implement support for updateProperties.highlighted in browser.tabs.update()"). Thus the integration will become available on Firefox 63 or later.

**Comment by piroor** [comment]
This is done by recent commits. You can try it with the latest development build.

As the result, now most features of this addon (close selected tabs and others) become obsolete because Firefox itself provides same features. My plan for future of this addon is:

 * I'll release current master/HEAD (or future revisions) as the next stable version. It will become the last release of this addon.
 * But this addon has some unique features: Copy to Clipboard, Save Tabs to File, and so on. Thus I'll do something for each feature:
   - Maybe I create a separate single-feature addon supporting multiselection of Firefox 63 and later.
   - Maybe I send pull requests to existing single-feature addon to support multiselection of Firefox 63+ and TST's fake context menu.

**Comment by rayman89** [comment]
I think the addon is really useful even if firefox provides that functionality because the way the addon presents the tabs it's easier to select them from there when they far apart or when there are a lot of consecutive tabs so I don't really think is necessary to change it that much.

In my opinion I would keep the addon the same as its now with just the functionality you recently added. If you wanna go the extra step you could make the addon detect when the context menu is being opened from a tab  and hide some elements to avoid redundancy other than that the addon is great. Thank you.

**Comment by piroor** [comment]
I've updated my plan to keep MTH in development, because tab selection by dragging looks too much to integrate to TST itself.

 * After Firefox 63 is released, I'll remove codes to manage custom selection from MTH, and MTH will become an addon based on the native multiselection feature of Firefox 63. (So the minimum supported version of Firefox will become 63.)
 * Some duplicated features ("Close Selected Tabs" and others) will become available only on the selection panel. They will disappear from the menu item added to the Firefox's context menu.

**Comment by rayman89** [comment]
I tested v 2.1.3 downloaded from AMO and I see no differences from 2.1.2. Did you make the changes only usable for FF63? I have multiselection enabled on 62 but the new feature it's not working there. I tested on a clean profile.

**Comment by rayman89** [comment]
I tested on FF 63 and it works properly but when an action is performed on the tabs they get unselected. This does not happen when using firefox default commands. I think it would be nice to keep them selected to be able for example to copy the url of the selected tabs and then close them also for the sake of consistency with vanilla firefox.

**Comment by piroor** [comment]
It is one of differences between Firefox's native multiselection and MTH's classic behavior. By the commit 081ce62460c50e0553291ed70f95e4d7785b0fc7 the default behavior becomes same to Firefox's native.

**Comment by Kilbourne** [comment]
The "Selected Tabs" context menu disappeared after updating to 2.2.4

**Comment by rayman89** [comment]
For me it's there still.

**Comment by piroor** [comment]
I've realized that some problems around operations to update menu items. By recent commits context menu items are now correctly updated for me so I hope this issue become solved.

**Comment by Kilbourne** [comment]
2.2.5 resolves the problem for me. Thanks!
