### ISSUE TITLE
Ghost tabs

### ISSUE THREAD

**Issue by mapsonx** [piroor/multipletab#92]
Even on a fresh profile with only MTH and session manager installed, I'm getting what can only describe as ghost/shadow tabs...new blank tabs that cannot be closed, and when clicked on actually open the tab to the right, and sometimes also duplicate each other when clicked on or after a fresh browser launch.

Is there a list of known extensions that Multiple tab handlers has problems with? I'm also experiencing some Fx crashing.

---

Fx 38.06, xp sp3, Multiple Tab Handler 0.8.2015030601.1-signed

**Comment by rayman89** [comment]
I think this issue is caused by tab mix plus cause I got the same issue while using auto unload tab and tab mix plus together and changing tab mix plus for tab utilities fixed solved it. 

BTW use the nightly/beta version of the add-ons since piro takes it's time to update it in AMO

http://piro.sakura.ne.jp/xul/xpi/nightly/

**Comment by piroor** [comment]
Outdated.
